#! /bin/bash

# For Testing
INSTRUCTOR_SCRIPTS="/home/.evaluationScripts"
# INSTRUCTOR_SCRIPTS="."
LAB_DIRECTORY="../labDirectory"

# Store current directory
ptcd=$(pwd)

# Change to instructor scripts directory
cd $INSTRUCTOR_SCRIPTS

# # List all .sh files in lab directory
# list_of_files="$(ls $LAB_DIRECTORY | grep '\.sh$')"

# Copy lab directory files to autograder directory
cp -r $LAB_DIRECTORY/*.sh autograder/

# Change to autograder directory
cd ./autograder/

# Make listed files executable
chmod 777 submission1.sh
chmod 777 submission2.sh
chmod 777 submission3.sh

# Execute grader script
./grader.sh

# Clean up: Delete files and folders generated by grader.sh if they exist
# Assuming these are the files/folders that might be generated by grader.sh
generated_files=("fold1" "fold2" "fold3" "fold4" "fold5" "file.tgz" "file.tar.bz2" "file.tar.xz" "submission1.sh" "submission2.sh" "submission3.sh")

for item in "${generated_files[@]}"; do
  if [ -e "$item" ]; then
    rm -r "$item"
  fi
done

# Return to the previous directory
cd "$ptcd"
